export default [
  {
    username: "Admin",
    shipName: "ABC",
    nameCode: "A01",
    email: "abc@gmail.com",
    website: "abc.com.vn",
    phone: "0359049292",
    icds: ["Dry port", "Seaport"],
    address: "abc xyz",
    password: "123456",
    role: ["ROLE_SHIPPINGLINE"],
    status: "ACTIVE"
  },
  {
    username: "Admin",
    shipName: "ABC",
    nameCode: "A02",
    email: "abc@gmail.com",
    website: "abc.com.vn",
    phone: "0359049292",
    icds: ["Dry port", "Seaport"],
    address: "abc xyz",
    password: "123456",
    role: ["ROLE_SHIPPINGLINE"],
    status: "ACTIVE"
  },
  {
    username: "Admin",
    shipName: "ABC",
    nameCode: "A03",
    email: "abc@gmail.com",
    website: "abc.com.vn",
    phone: "0359049292",
    icds: ["Dry port", "Seaport"],
    address: "abc xyz",
    password: "123456",
    role: ["ROLE_SHIPPINGLINE"],
    status: "ACTIVE"
  },
  {
    username: "Admin",
    shipName: "ABC",
    nameCode: "A04",
    email: "abc@gmail.com",
    website: "abc.com.vn",
    phone: "0359049292",
    icds: ["Dry port", "Seaport"],
    address: "abc xyz",
    password: "123456",
    role: ["ROLE_SHIPPINGLINE"],
    status: "ACTIVE"
  },
  {
    username: "Admin",
    shipName: "ABC",
    nameCode: "A05",
    email: "abc@gmail.com",
    website: "abc.com.vn",
    phone: "0359049292",
    icds: ["Dry port", "Seaport"],
    address: "abc xyz",
    password: "123456",
    role: ["ROLE_SHIPPINGLINE"],
    status: "ACTIVE"
  },
  {
    username: "Admin1",
    shipName: "ABC",
    nameCode: "A06",
    email: "abc@gmail.com",
    website: "abc.com.vn",
    phone: "0359049292",
    icds: ["Dry port", "Seaport"],
    address: "abc xyz",
    password: "123456",
    role: ["ROLE_SHIPPINGLINE"],
    status: "ACTIVE"
  },
  {
    username: "Admin1",
    shipName: "ABC",
    nameCode: "A07",
    email: "abc@gmail.com",
    website: "abc.com.vn",
    phone: "0359049292",
    icds: ["Dry port", "Seaport"],
    address: "abc xyz",
    password: "123456",
    role: ["ROLE_SHIPPINGLINE"],
    status: "ACTIVE"
  },
  {
    username: "Admin",
    shipName: "ABC",
    nameCode: "A08",
    email: "abc@gmail.com",
    website: "abc.com.vn",
    phone: "0359049292",
    icds: ["Dry port", "Seaport"],
    address: "abc xyz",
    password: "123456",
    role: ["ROLE_SHIPPINGLINE"],
    status: "ACTIVE"
  }
];
